### ISSUE TITLE
Error 404 for some pages in https://algorithm.yuanbin.me/zh-hans

### ISSUE THREAD

**Issue by xuanus** [billryan/algorithm-exercise#121]
The following pages are returning 404 errors.
https://algorithm.yuanbin.me/zh-hans/linked_list/delete_node_in_the_middle_of_singly_linked_list
https://algorithm.yuanbin.me/zh-hans/basics_algorithm/counting_problem
https://algorithm.yuanbin.me/zh-hans/dynamic_programming/egg_dropping_puzzle
https://algorithm.yuanbin.me/zh-hans/data_structure/kth_smallest_number_in_sorted_matrix
https://algorithm.yuanbin.me/zh-hans/problem_misc/n_queens
https://algorithm.yuanbin.me/zh-hans/problem_misc/n_queens_ii
https://algorithm.yuanbin.me/zh-hans/appendix_ii_system_design

**Comment by billryan** [comment]
These pages are draft markdown. I will remove these entries in GitBook SUMMARY.md.
