### ISSUE TITLE
add tabs-navigation?

### ISSUE THREAD

**Issue by y4h2** [billryan/algorithm-exercise#16]
有没有必要加个tab navigation? 类似九章上面的，http://www.jiuzhang.com/solutions/anagrams/。
把C++、python、java代码分tab显示， 我觉得这样会让页面更简洁一点

**Comment by billryan** [comment]
这个在 gitbook 里实现目前有点困难，需要自己写 javascript 插件，而且需要自定义模板语法。暂时先完善 markdown 源文档吧，类似这种增强可读性的后期处理在计划中。

**Comment by billryan** [comment]
@Shaunwei Any idea about this feature?

**Comment by Shaunwei** [comment]
其实按照可读性来说，我不是很喜欢tab，因为没有办法很直观的看到所有语言在实现同一算法的区别。而且九章的那个tab功能对手机非常不friendly。

**Comment by billryan** [comment]
你这么一说我也觉得 tab 确实不是很好的设计，还是维持现在这种最简单的方式好了

**Comment by billryan** [comment]
codetab 现已有插件 https://github.com/GitbookIO/plugin-codetabs
看了下 toc 相关的插件，没有一款简单好用的，于是自己写了一个 https://github.com/billryan/gitbook-plugin-etoc

![screenshot 2016-09-07 23 00 26](https://cloud.githubusercontent.com/assets/1292567/18316915/f26e401c-754e-11e6-9a63-ec3763e4e385.png)
