### ISSUE TITLE
I was planned to do similar thing, but ...

### ISSUE THREAD

**Issue by wilbeibi** [billryan/algorithm-exercise#19]
看了 lz 的 repo，觉得我的可以不用弄了，逐渐把我[笔记和代码](https://github.com/Wilbeibi/JourneyToGreatness)里有用的东西搬运过来。

**Comment by billryan** [comment]
( ⊙o⊙ )哇 你刷的题好多啊，欢迎 PR~ 或者我直接把你加到 Contributor 里?

**Comment by wilbeibi** [comment]
我有空的时候给你 pull request 呗。。。最近在面试。。。

**Comment by billryan** [comment]
Best Wishes. :)

2015-08-05 10:47 GMT+08:00 Hongyi Shen notifications@github.com:

> 我有空的时候给你 pull request 呗。。。最近在面试。。。
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/billryan/algorithm-exercise/issues/19#issuecomment-127825054
> .

## 

from: billryan
Email: yuanbin2014@gmail.com
